<Project>
  <PropertyGroup>
    <CodeIslandVersion>1.1.2</CodeIslandVersion>
    <Version>$(CodeIslandVersion)</Version>
    <AssemblyVersion>$(CodeIslandVersion).0</AssemblyVersion>
    <FileVersion>$(CodeIslandVersion).0</FileVersion>
    <InformationalVersion>$(CodeIslandVersion)</InformationalVersion>
    <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
  </PropertyGroup>
</Project>
